@extends('layouts.appf')
@section('content')
@include('themes.aksataedu.partials.slider')
@include('themes.aksataedu.partials.about-profile')
@include('themes.aksataedu.partials.org-profile')
@include('themes.aksataedu.post.main-news-new')
@include('themes.aksataedu.partials.statistic')
@include('themes.aksataedu.blog.main-blog-new')
@endsection
