<?php

return [
    App\Providers\AgendaServiceProvider::class,
    App\Providers\AlbumServiceProvider::class,
    App\Providers\AnnouncementServiceProvider::class,
    App\Providers\AppServiceProvider::class,
    App\Providers\BlogServiceProvider::class,
    App\Providers\BlogcategoryServiceProvider::class,
    App\Providers\EmployeServiceProvider::class,
    App\Providers\PeformanceServiceProvider::class,
    App\Providers\PerformanceServiceProvider::class,
    App\Providers\StatisticServiceProvider::class,
    App\Providers\VideoServiceProvider::class,
    App\Providers\ViewHeadermenuServiceProvider::class,
    App\Providers\ViewMenuFotterleftServiceProvider::class,
    App\Providers\ViewMenuFottermiddleServiceProvider::class,
    App\Providers\ViewMenuFotterrightServiceProvider::class,
    App\Providers\ViewPostLatestServiceProvider::class,
    App\Providers\ViewPostcategoryServiceProvider::class,
    App\Providers\ViewSettingServiceProvider::class,
    App\Providers\ViewSocialmediaServiceProvider::class,
    App\Providers\ViewTagServiceProvider::class,
    App\Providers\ViewTopmenuServiceProvider::class,
];
